examples/wasmachine:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
  depends_components:
    - components/wasmachine_core
    - components/wasmachine_data_sequence
    - components/wasmachine_ext_wasm_native
    - components/wasmachine_ext_wasm_native_rainmaker
    - components/wasmachine_ext_wasm_vfs
    - components/wasmachine_shell