.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
  script:
    - echo "MODIFIED_FILES $MODIFIED_FILES"
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps==1.1.4
    - if [ -n "$SDKCONFIG_DEFAULTS" ] && [ -n "$IDF_TARGET" ]; then
        python tools/ci/build_apps.py --sdkconfig-defaults $SDKCONFIG_DEFAULTS -t $IDF_TARGET;
      else
        python tools/ci/build_apps.py;
      fi

build_platform_devkit:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
      - IMAGE: espressif/idf:release-v5.3
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:release-v5.1

build_platform_esp32s3_box:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: espressif/idf:latest
      - IMAGE: espressif/idf:release-v5.3
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    SDKCONFIG_DEFAULTS: sdkconfig.defaults;sdkconfig.esp-box